In [5]:
import numpy as np
import pandas as pd
data=pd.Series([0.25,0.5,0.75,1.0])
print(data.values)
print(data.index)

[0.25 0.5  0.75 1.  ]
RangeIndex(start=0, stop=4, step=1)

In [15]:
dic={'a':1,True:2,4:'k'}
change=pd.Series(dic)
change['a':4]

a       1
True    2
4       k
dtype: object

In [18]:
pd.Series({'a':1,'b':2,'c':3},index=['b','c','d'])

b    2.0
c    3.0
d    NaN
dtype: float64

In [31]:
population=pd.Series({'california':1,'florida':2})
area=pd.Series({'california':3,'florida':4})
states=pd.DataFrame(population,area,columns=['population','area'])
states

TypeError: unhashable type: 'Series'

In [33]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]
pd.DataFrame(data,index=['x','y','z'])

   a  b
x  0  0
y  1  2
z  2  4

In [6]:
data=[{'a':i,'b':i*2}for i in range(3)]
pd.DataFrame(data)

   a  b
0  0  0
1  1  2
2  2  4

In [22]:
import numpy as np
x=np.array([i for i in range(5)])
pd.DataFrame(x,index=['y','z','x','y','z'],columns=['x'])

   x
y  0
z  1
x  2
y  3
z  4

我草dtype还有此奇效

In [29]:
A=np.zeros(3, dtype=[('A', 'i8'), ('B', 'f8')])
print(A)
A

[(0, 0.) (0, 0.) (0, 0.)]

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [34]:
x=pd.Index(['a','b','c',1])
x[::-1]

Index([1, 'c', 'b', 'a'], dtype='object')

In [39]:
x=pd.Index(['a','b','c',1])
x.dtype

dtype('O')

In [13]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],index=['a', 'b', 'c', 'd'])
data['k']=7
data.items()

In [16]:
s='heel'
print(s.upper)

<built-in method upper of str object at 0x00000201FE651B70>

In [19]:
z = zip([1,2,3],[4,5,6])
print(z)

<zip object at 0x00000201FE6F0200>
[1, 2, 3] [4, 5, 6]

In [22]:
s = pd.Series([10,20,30], index=["a","b","c"])
s.items()

In [26]:
import pandas as pd

s = pd.Series([10,20,30], index=["a","b","c"])

x=s.items()
print(next(x))
print(next(x))
print(next(x))
print(next(x))

('a', 10)
('b', 20)
('c', 30)

StopIteration:

In [4]:
import pandas as pd
area = pd.Series({'California': 423967, 'Texas': 695662,
'New York': 141297, 'Florida': 170312,
'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127, 'Florida': 19552860,
'Illinois': 12882135})
data = pd.DataFrame({'column0':area, 'column1':pop})
data['California':'Illinois']

            column0   column1
California   423967  38332521
Texas        695662  26448193
New York     141297  19651127
Florida      170312  19552860
Illinois     149995  12882135

In [5]:
import numpy as np

np.random.seed(42)

a = np.random.randint(0,10)

np.random.randint(0,10)  # 模拟别的代码

b = np.random.randint(0,10)

print(a, b)

6 7

In [6]:
rng = np.random.RandomState(42)

a = rng.randint(0,10)

np.random.randint(0,10)  # 别的代码

b = rng.randint(0,10)

print(a, b)

6 3

In [9]:
import pandas as pd
import numpy as np
rng=np.random.RandomState(4)
data=pd.DataFrame(rng.randint(0,10,(3,4)),index=['a','b','c'],columns=['A', 'B', 'C', 'D'])
np.exp(data)

             A            B            C            D
a  1096.633158   148.413159     2.718282  2980.957987
b  1096.633158  2980.957987     7.389056  8103.083928
c  1096.633158  1096.633158  1096.633158  8103.083928

In [11]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
'New York': 19651127}, name='population')
print(area, population)

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64 California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64

In [12]:
list('AB')

['A', 'B']